### ISSUE TITLE
Darkmode

### ISSUE THREAD

**Issue by simenandre** [bjerkio/website#101]
I would love to have a dark mode. After making my desktop change from light/dark mode dependent on time, its so annoying when I open a light mode-only website at night.

It's also kinda cool, and kinda a developer thing.

Thoughts?

/cc @AnneMatilde @AnnaBjerk @seacurrent @dkostenko-bjerk

**Comment by AnneMatilde** [comment]
I agree! That would give the site an edge.

**Comment by AnnaBjerk** [comment]
What she said! :point_up_2: 🎉

**Comment by AnnaBjerk** [comment]
So if everyone agrees, let's go for it! Do we need separate design for it, @AnneMatilde ??

/cc: @cobraz

**Comment by AnneMatilde** [comment]
What do you think @dkostenko-bjerk? How would you like work on dark mode? Do you want complete design files in dark mode?

**Comment by dkostenko-bjerk** [comment]
@AnneMatilde I think we just need to agree on what color will be where, and most likely we need to change the color of the images

**Comment by cobraz** [comment]
We can use this:
https://theme-ui.com/color-modes/

**Comment by AnnaBjerk** [comment]
> I would love to have a dark mode. After making my desktop change from light/dark mode dependent on time, its so annoying when I open a light mode-only website at night.
> 
> It's also kinda cool, and kinda a developer thing.
> 
> Thoughts?

Do you mean that you would like Bjerk-site to be light sensitive and change to dark mode automatically, @cobraz ? Or should it be a free-to-choose option with a button like here on GitHub?

**Comment by cobraz** [comment]
Maybe both? At least use [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) 👍
