### ISSUE TITLE
Markdown content

### ISSUE THREAD

**Issue by dkostenko-bjerk** [bjerkio/website#106]
@cobraz @seacurrent @AnneMatilde @AnnaBjerk

How will we organize the markdown content and what pages (elements) will we render this way?

Referring to #93 (comments)

**Comment by AnnaBjerk** [comment]
As we discussed earlier today, your suggestion is to split the content, right? 
So, if I understand this correctly, you suggested to use md-tags for texts and such and use .mdx files for illustration-based signs/images?

**Comment by cobraz** [comment]
> As we discussed earlier today, your suggestion is to split the content, right?

We probably want to split the files logically into folders with some sensible naming.

> You meant to split the entire content into pages that will or will not use markdown? Referring to your last question here #74
> > @cobraz what content besides projects needs to be done with markdown?

I think we want blog articles, projects and employees, anything else?

> Can we use md-tags for texts and such and use .mdx files for illustration-based signs/images? Referring to the discussion here #93

Probably keep that discussion there in #93?

/cc @seacurrent

**Comment by AnnaBjerk** [comment]
> We probably want to split the files logically into folders with some sensible naming.

That makes sense! 

> I think we want blog articles, projects and employees, anything else?

Not that I can think of right now

@cobraz @dkostenko-bjerk

**Comment by dkostenko-bjerk** [comment]
> I think we want blog articles, projects and employees, anything else?
I think nothing else, but we need to take a closer look at md tags for projects (question in #93)

**Comment by cobraz** [comment]
After looking at #108, #109, #103 I realize that we probably want if not all, but most of the content in either Markdown or MDX. Using Javascript objects isn't the best user experience, at least not for novice users.

Since Markdown/MDX files are essentially _just data_, they can be used to propagate our GraphQL API for all kinds of data. One example is under the services page, where currently have a few pictures of employees and some service. This could be defined like this in Markdown:

```markdown
---
name: Programming
title: Applikasjons- og programvareutvikling
url-navigation-link: ''
url-link-text: Book et møte med Simen
image: SimenBox.png
---

Har du ideer for en applikasjon eller trenger kanskje bedriften din et program for en
smidigere hverdag? Vi i Bjerk kan hjelpe deg med alt fra utvikling og integrering av
programvare til applikasjoner slik at arbeidshverdagen din blir automatisert og dermed
mer effektiv. Vår meget dyktige løsningsarkitekt og Head of Developing Team - Simen - kan
hjelpe deg med å finne den beste løsningen for din ide.
```

We probably would want to put all these Markdown/MDX files in a separate folder, specifically for content, we would get a somewhat improved user experience. This would consequently help us with localization (#23) too.

**Comment by dkostenko-bjerk** [comment]
I created this structure for MDX files for content objects (employees, about articles, services articles)

![image](https://user-images.githubusercontent.com/79641914/112631938-9136a880-8e48-11eb-9ea8-ee2863a6e3f4.png)

and this structure for MDX files for projects pages (with the project page template other file)

![image](https://user-images.githubusercontent.com/79641914/112632174-d35fea00-8e48-11eb-962c-2dac11bcb55f.png)

**Comment by dkostenko-bjerk** [comment]
Can we group all the content in React components to the MD files and get it by graphql call like these 👆?
Or will we use [this](https://github.com/wiziple/gatsby-plugin-intl/blob/master/examples/gatsby-starter-default-intl/src/intl/en.json) example for the [gatsby-plugin-intl](https://www.gatsbyjs.com/plugins/gatsby-plugin-intl/) localization library for #23

**Comment by AnnaBjerk** [comment]
> I created this structure for MDX files for content objects (employees, about articles, services articles)
> 
> ![image](https://user-images.githubusercontent.com/79641914/112631938-9136a880-8e48-11eb-9ea8-ee2863a6e3f4.png)
> 
> and this structure for MDX files for projects pages (with the project page template other file)
> 
> ![image](https://user-images.githubusercontent.com/79641914/112632174-d35fea00-8e48-11eb-962c-2dac11bcb55f.png)

I like how organized and transparent this looks

**Comment by cobraz** [comment]
Yeah, I like it. 👍
