### ISSUE TITLE
Text size and placement

### ISSUE THREAD

**Issue by AnnaBjerk** [bjerkio/website#115]
As mentioned in PR #109 

> The text has the wrong size and weight – this is throughout the subpages.
> 
> This is how it looks now:
> ![image](https://user-images.githubusercontent.com/54155334/112437147-eab6ae80-8d46-11eb-87ea-d3c68953d198.png)
> 
> And this is how it should look:
> ![image](https://user-images.githubusercontent.com/54155334/112437175-f3a78000-8d46-11eb-84ae-1471a84e3fce.png)
> 
> Header is missing background on scroll.
> 
> Text underneath the pictures is also too small and squeezed:
> ![image](https://user-images.githubusercontent.com/54155334/112437266-0d48c780-8d47-11eb-9203-cdcda3d5ceba.png)

/cc: @AnneMatilde

**Comment by dkostenko-bjerk** [comment]
I think this issue will be part of the main font issue for the entire site
