### ISSUE TITLE
Add `gatsby-image`

### ISSUE THREAD

**Issue by cobraz** [bjerkio/website#132]
We probably want to load images with `gatsby-image`. It loads image _way_ better than what we got.

## References

- https://www.gatsbyjs.com/plugins/gatsby-image/

**Comment by dkostenko-bjerk** [comment]
@cobraz Do you want to get images from GraphQL query or to use the Image component from 'gatsby' package?

**Comment by cobraz** [comment]
What we want is dynamic images (as such the images load from bad to good quality). This seriously improves loading :)

**Comment by dkostenko-bjerk** [comment]
@cobraz How do you want to select the quality? In code or somewhere in config file?

**Comment by cobraz** [comment]
> @cobraz How do you want to select the quality? In code or somewhere in config file?

Probably in the configuration somewhere? 🤷‍♂️
