### ISSUE TITLE
English version text

### ISSUE THREAD

**Issue by AnnaBjerk** [bjerkio/website#140]
Right now the button "Engelsk versjon" is in Norwegian. I'm thinking that it might make more sense to have it in English since it's directed at an english speaking audience. And the English site has the button "Norwegian version". Not sure about this one. Also, would it maybe be easier to remove the word "versjon/version" completely? 

What are your thouhgts on this? 

@cobraz @AnneMatilde @seacurrent 

![Screenshot 2021-03-31 11 17 59](https://user-images.githubusercontent.com/73297506/113123318-c2322700-9214-11eb-924a-6b69564ab5f2.png)
![Screenshot 2021-03-31 11 18 07](https://user-images.githubusercontent.com/73297506/113123297-bcd4dc80-9214-11eb-81d0-c3c81db3b2e4.png)

**Comment by cobraz** [comment]
IMHO, it doesn't make sense to have that text there at all. It should be in the footer, or maybe not visible at all?

Also, only write «English» IMHO.
