### ISSUE TITLE
Scaling issues on smaller screens

### ISSUE THREAD

**Issue by AnneMatilde** [bjerkio/website#147]
We should fix the footer on tablet:

iPad Pro: 
![image](https://user-images.githubusercontent.com/54155334/113141524-17c4fe80-922a-11eb-8ead-7a8bbe2e72ce.png)

iPad: 
![image](https://user-images.githubusercontent.com/54155334/113141584-2b706500-922a-11eb-9ddb-abd5a8537640.png)

**Comment by dkostenko-bjerk** [comment]
@AnneMatilde Should it be like a on a big screen or like on mobile?

**Comment by dkostenko-bjerk** [comment]
@cobraz Can you help with it?

**Comment by AnnaBjerk** [comment]
@AnneMatilde @dkostenko-bjerk The first photo is what it looks like on my laptop as well.

![Screenshot 2021-03-31 15 57 49](https://user-images.githubusercontent.com/73297506/113156916-b6f1f200-923a-11eb-9141-107ca7cb450e.png)

**Comment by dkostenko-bjerk** [comment]
How should it look without changing the font size? like on a mobile device or just close to each other without text wrapping?

**Comment by AnneMatilde** [comment]
It should go to this:
![image](https://user-images.githubusercontent.com/54155334/113163261-46e66a80-9240-11eb-93c6-3ead8483269b.png)

And then to this:
![image](https://user-images.githubusercontent.com/54155334/113163295-52d22c80-9240-11eb-9d37-a5531f7c7875.png)

And then to mobile.
