### ISSUE TITLE
Font is too thick

### ISSUE THREAD

**Issue by AnneMatilde** [bjerkio/website#152]
The font in the nav menu and on all headings is too thick. It should be _DemiBold_.

**Comment by AnnaBjerk** [comment]
So, not this: 

![Screenshot 2021-04-06 09 11 44](https://user-images.githubusercontent.com/73297506/113672667-550d0e80-96b8-11eb-8c00-06e06189b3b2.png)
 But this: 
 
 
![Screenshot 2021-04-06 09 11 48](https://user-images.githubusercontent.com/73297506/113672704-5cccb300-96b8-11eb-8d0f-21ddff2b19c7.png)

**Comment by cobraz** [comment]
@AnneMatilde How're the fonts now? Can we close this?

**Comment by AnneMatilde** [comment]
Fonts are looking good!
