### ISSUE TITLE
Footer plant not correct color and position

### ISSUE THREAD

**Issue by AnneMatilde** [bjerkio/website#153]
The plant is not the right color and does not have the right positioning.

How it looks now:
![image](https://user-images.githubusercontent.com/54155334/113163807-cd02b100-9240-11eb-94a0-b2b7fed0d659.png)

How it should look:
![image](https://user-images.githubusercontent.com/54155334/113163907-e6a3f880-9240-11eb-80d8-109755db9863.png)

**Comment by AnneMatilde** [comment]
This is of course a result of removing the contact footer.

**Comment by cobraz** [comment]
Outdated right now, we should reintroduce the illustration at some point tho'.
