### ISSUE TITLE
Buttons without action on url:https://bjerk.io/services

### ISSUE THREAD

**Issue by seacurrent** [bjerkio/website#162]
![Skjermbilde 2021-04-07 kl  13 52 11](https://user-images.githubusercontent.com/70881117/113862312-882ecb00-97a8-11eb-9448-982f491e96a1.png)

When pressing this button, and the two others on that page nothing happens. Are they not supposed to send an email?

**Comment by cobraz** [comment]
Outdated right now, we should probably reintroduce this at some point tho'.
