### ISSUE TITLE
Links from frontpage https://bjerk.io/

### ISSUE THREAD

**Issue by seacurrent** [bjerkio/website#163]
![Skjermbilde 2021-04-07 kl  13 54 57](https://user-images.githubusercontent.com/70881117/113862704-0db27b00-97a9-11eb-9442-c0feb3fa628b.png)
When clicking these links user should bes sent to the correct part of the page. https://bjerk.io/services
But all three just sends user to the top of the page.

**Comment by cobraz** [comment]
Outdated right now, we should probably reintroduce these at some point tho'.
