### ISSUE TITLE
Home contact block

### ISSUE THREAD

**Issue by TanyaDolgopolova** [bjerkio/website#21]
I need a video from this block. Is there an action that should be performed when this button is clicked? (except navigation to contact page)

<img width="1044" alt="Screenshot 2021-01-25 at 15 30 26" src="https://user-images.githubusercontent.com/35150766/105712298-410f9880-5f22-11eb-8ecf-173131608cdc.png">

**Comment by cobraz** [comment]
We should probably store a YouTube-URL for that video in Sanity.

**Comment by TanyaDolgopolova** [comment]
Okay, do we have url?

**Comment by cobraz** [comment]
I don't know what the URL will be, but it should be changeable in Sanity.

You can just pick a video from YT now. The thumbnail should also be "changeable".

**Comment by TanyaDolgopolova** [comment]
@cobraz do we need design now? Cause we backlog developing appointments

**Comment by cobraz** [comment]
We can leave it until we have groomed this.
