### ISSUE TITLE
Links to social networks

### ISSUE THREAD

**Issue by TanyaDolgopolova** [bjerkio/website#22]
Need links to all social media on footer component
Related to #28 

<img width="1029" alt="Screenshot 2021-01-25 at 15 32 56" src="https://user-images.githubusercontent.com/35150766/105712571-a5caf300-5f22-11eb-9a60-2a6b4774f3e6.png">

**Comment by cobraz** [comment]
@AnneMatilde Are these icons from an icon library or something?

**Comment by AnneMatilde** [comment]
No, the icons are made by me. I can add the svgs.
Github: https://github.com/bjerkio
Linkedin: https://www.linkedin.com/company/bjerk/
Facebook: https://www.facebook.com/WeAreDigitalization
Instagram: REMOVE

**Comment by TanyaDolgopolova** [comment]
@AnneMatilde thank you 🙏
