### ISSUE TITLE
Workflow error when using action-hosting-deploy

### ISSUE THREAD

**Issue by ws333** [bjerkio/website#229]
`Error: Input required and not supplied: firebaseServiceAccount`

Opened issue: https://github.com/FirebaseExtended/action-hosting-deploy/issues/134
Edit: Found the cause so closed the issue, see comment below.

**Comment by ws333** [comment]
This seems to be the cause: https://github.com/dependabot/dependabot-core/issues/3253#issuecomment-852541544


> For GitHub Actions workflows initiated by Dependabot (github.actor == "dependabot[bot]") using the pull_request, pull_request_review, pull_request_review_comment, and push events:
> 
>     your GITHUB_TOKEN is read-only
>     secrets are inaccessible

**Comment by ws333** [comment]
@cobraz Would you like me to make the changes?

**Comment by cobraz** [comment]
Yeah, let's try that 👍
