### ISSUE TITLE
Localization (i18n)

### ISSUE THREAD

**Issue by cobraz** [bjerkio/website#23]
Nick and I have had a few talks about the fact that we would like to have an english-translation for the Bjerk site in a not so distant future. That fact would make adding some localization libraries make sense.

Considering we're using Gatsby, maybe we should consider adding the translations in build-time? Whats the standards for i18n for Gatsby users?

/cc @seacurrent @TanyaDolgopolova

**Comment by TanyaDolgopolova** [comment]
I think we can use: [gatsby-theme-i18n](https://www.gatsbyjs.com/plugins/gatsby-theme-i18n/?=i18) with [gatsby-theme-i18n-react-intl](https://github.com/gatsbyjs/themes/tree/master/packages/gatsby-theme-i18n-react-intl). 

The first creates prefixed, enriched pages for each language and second provide localization support

**Comment by cobraz** [comment]
Sounds good!

Any feedback, @seacurrent ?

**Comment by TanyaDolgopolova** [comment]
@cobraz I just thought that since our content will change in Sanity, it may be difficult to connect translation through these packages. Right now I can only suggest adding fields with Norwegian and English translation to Sanity and check which language we need in the application

**Comment by dkostenko-bjerk** [comment]
@cobraz I think that [gatsby-plugin-intl](https://www.gatsbyjs.com/plugins/gatsby-plugin-intl/) is a good decision

**Comment by AnnaBjerk** [comment]
@cobraz Let's finish grooming this today! 😸 👍

**Comment by AnnaBjerk** [comment]
> Sounds good!
> 
> Any feedback, @seacurrent ?

Could we please get your opinion on this issue @seacurrent so @dkostenko-bjerk can start working on this?

**Comment by seacurrent** [comment]
what do you want my comment on?

**Comment by cobraz** [comment]
@dkostenko-bjerk Use [gatsby-plugin-intl](https://www.gatsbyjs.com/plugins/gatsby-plugin-intl/) if you feel that works!

We probably would need to do a few iterations on this anyway 👍
