### ISSUE TITLE
Make an appointment

### ISSUE THREAD

**Issue by TanyaDolgopolova** [bjerkio/website#24]
How we will resolve booking?

<img width="997" alt="Screenshot 2021-01-25 at 16 33 31" src="https://user-images.githubusercontent.com/35150766/105719550-137b1d00-5f2b-11eb-8ad7-9beeb9eabb0e.png">

**Comment by cobraz** [comment]
I don't know. This should be handled by some external API of some sorts.

Let me think on it for a while, until we have it groomed let's just backlog it.
