### ISSUE TITLE
Button animation

### ISSUE THREAD

**Issue by TanyaDolgopolova** [bjerkio/website#25]
I see that on some pages we have animation on buttons, but not on all of them. Do we need animation (increase and decrease arrow) on all buttons?

<img width="169" alt="Screenshot 2021-01-25 at 16 44 03" src="https://user-images.githubusercontent.com/35150766/105720821-8b961280-5f2c-11eb-87bf-1c11e67882f5.png">

**Comment by cobraz** [comment]
@AnneMatilde 👆

**Comment by AnneMatilde** [comment]
Yes, use the same button with animation on the whole website.
