### ISSUE TITLE
Change header with new design

### ISSUE THREAD

**Issue by TanyaDolgopolova** [bjerkio/website#27]
Header flow:
1. Scroll is on the top of window - header is transparent, white text;
2. User scrolled under video - header is white with black text;

<img width="1044" alt="Screenshot 2021-01-25 at 17 58 17" src="https://user-images.githubusercontent.com/35150766/105730334-e896c600-5f36-11eb-8d62-6c9e3959f2dc.png">

**Comment by cobraz** [comment]
Which part? The navigation should probably be defined there, yeah. But we don't need to do that first, for now, we'll just hardcode it. What do you think?

**Comment by TanyaDolgopolova** [comment]
I think that header should not be connected to Sanity. It may will work if we will have predefined pages on Sanity. But the best option for now is to create page on gatsby, cause we have more complex design
