### ISSUE TITLE
Update footer with new design

### ISSUE THREAD

**Issue by TanyaDolgopolova** [bjerkio/website#28]
<img width="1049" alt="Screenshot 2021-01-25 at 18 02 57" src="https://user-images.githubusercontent.com/35150766/105730957-9013f880-5f37-11eb-9b77-1caf58b94a96.png">

**Comment by TanyaDolgopolova** [comment]
@cobraz do I need connect footer content to the Sanity?

**Comment by TanyaDolgopolova** [comment]
@AnneMatilde what actions need to be after clicking on phone number or email?

**Comment by TanyaDolgopolova** [comment]
> @AnneMatilde what actions need to be after clicking on phone number or email?

@cobraz

**Comment by cobraz** [comment]
Answered in #33 :)

**Comment by AnnaBjerk** [comment]
#33 closes this issue
