### ISSUE TITLE
Add new component to the footer of the page

### ISSUE THREAD

**Issue by TanyaDolgopolova** [bjerkio/website#29]
- [ ] design
- [ ] connect to Sanity

<img width="638" alt="Screenshot 2021-01-25 at 18 04 11" src="https://user-images.githubusercontent.com/35150766/105731124-bc2f7980-5f37-11eb-8ae6-826521bf833f.png">

**Comment by cobraz** [comment]
Do we want to devide the form into a separate component or this whole section as one?

**Comment by TanyaDolgopolova** [comment]
Yes, the best options is divide form into a separate component. This will make the code look more structured
