### ISSUE TITLE
Text elements are not separeted by `<br />`

### ISSUE THREAD

**Issue by braaar** [bjerkio/website#312]
At https://bjerk.io/about we see that the sentence 'Open source code also gives...' starts right after the previous sentence, with no spacing, even though it is defined as a separate `Text` element in the source code. 

https://github.com/bjerkio/website/blob/bfb03da07b7b693726685c3a627a235a4ae67bd0/src/pages/about.en.tsx#L32

**Comment by cobraz** [comment]
Should probably use Paragraph instead?

**Comment by braaar** [comment]
> Should probably use Paragraph instead?

I guess, but I'm confused as to why it behaves like this. Theme UI's Text should behave just like a `<p>`

**Comment by cobraz** [comment]
I don't think so, `Text` is not a paragraph. `<p />` and `<Paragraph />` is a paragraph

See the source code: https://github.com/system-ui/theme-ui/blob/develop/packages/components/src/Text.js
