### ISSUE TITLE
caching `.next` folder on build/export

### ISSUE THREAD

**Issue by braaar** [bjerkio/website#339]
I suspect that our github action could be caching the `out` folder. 

This could be causing some actions to fail because they are inheriting some bad stuff in the `out` folder from the cache, even though the code itself is fine.

**Comment by cobraz** [comment]
There's only caching of `.next`.

**Comment by braaar** [comment]
Just realised my mistake. It is indeed the `.next` folder which is likely causing the problem.

**Comment by braaar** [comment]
See this PR: https://github.com/bjerkio/website/pull/333

**Comment by braaar** [comment]
Why did the build/export action suddenly fail due to image optimisation things when I changed the `target` attribute of a link?

**Comment by braaar** [comment]
`yarn build` runs fine on my local machine.
