### ISSUE TITLE
Dynamically create link to projects

### ISSUE THREAD

**Issue by TanyaDolgopolova** [bjerkio/website#35]
**We need to build pages from the content from Sanity.**

I think we can add description of every project to the homepage:
<img width="417" alt="Screenshot 2021-01-27 at 20 03 27" src="https://user-images.githubusercontent.com/35150766/106033829-d3f33300-60da-11eb-9e1d-8a9fe17e5007.png">

And on `gatsby-node.js` we can create pages from the content that we added on sanity:
<img width="422" alt="Screenshot 2021-01-27 at 20 03 47" src="https://user-images.githubusercontent.com/35150766/106033783-c63dad80-60da-11eb-90ea-10520aa592be.png">

The link for how to do it: https://www.gatsbyjs.com/docs/sourcing-from-sanity/#generating-pages
@cobraz what do you think?

**Comment by AnnaBjerk** [comment]
@dkostenko-orion Do you have access to this?
