### ISSUE TITLE
Navigation to services

### ISSUE THREAD

**Issue by TanyaDolgopolova** [bjerkio/website#36]
**Suggestion to improve user navigation.**

When we navigate from home page to the page with services I think that we have not only navigate to the top of the page.
I suggest add sections to the services, so after clicking on this:

<img width="130" alt="Screenshot 2021-01-27 at 20 15 57" src="https://user-images.githubusercontent.com/35150766/106035176-795ad680-60dc-11eb-83cd-ec74b388a160.png">

We will easily navigate to the section of this service:
<img width="395" alt="Screenshot 2021-01-27 at 20 17 33" src="https://user-images.githubusercontent.com/35150766/106035350-b3c47380-60dc-11eb-87f8-597407c4052b.png">

@cobraz @seacurrent what do you think?

**Comment by cobraz** [comment]
@AnneMatilde should give some opinions on this. I dunno 🤷‍♂️

**Comment by AnnaBjerk** [comment]
@AnneMatilde Maybe you have time to look at this suggestion tonight?

**Comment by AnneMatilde** [comment]
Hey! I agree with you @TanyaDolgopolova. That's what I was thinking, but I didn't explain it anywhere, so thank you for suggesting! :-)
