### ISSUE TITLE
Footer, size and color

### ISSUE THREAD

**Issue by AnneMatilde** [bjerkio/website#426]
Hello @cobraz and @moripen! I have adjusted the font-size in the footer. And I see that the color should be much lighter. 
![image](https://user-images.githubusercontent.com/54155334/177095203-71259d71-72ea-4ee4-a034-0e633b630497.png)

New design:
![image](https://user-images.githubusercontent.com/54155334/177095773-2dc9b577-678b-4e8f-a858-1266d1add4ff.png)

Font size: 20px
Color: Blue40, #8FA1FF

**Comment by moripen** [comment]
Made a PR on this now called "footeradjustment"
![image](https://user-images.githubusercontent.com/107696180/177102719-ced28ea5-8af1-48ed-a83e-15578d98735b.png)

**Comment by moripen** [comment]
Fixed!
