### ISSUE TITLE
Linking to terms and privacy

### ISSUE THREAD

**Issue by moripen** [bjerkio/website#572]
Do we want to link to these pages in the footer? How do we want it to look?

**Comment by braaar** [comment]
Maybe a giant pop up that blocks the entire screen?

**Comment by moripen** [comment]
Hmm, yeah we should maybe have a GDPR-popup maybe? But I was more thinking of how we want to link to /terms and /privacy.

**Comment by moripen** [comment]
I will make a separate issue on the GDPR-popup.
