### ISSUE TITLE
Text placement on main page

### ISSUE THREAD

**Issue by moripen** [bjerkio/website#578]
The text: "Vi vil skape..." is aligned with the logo in the header while the "samarbeid, samspill..." is not.
![bilde](https://github.com/bjerkio/website/assets/107696180/e47ecbf5-79e7-4312-8e20-2038eb6d4a30)
This gives the feeling - at least personally - that the "samarbeid..."-part is off center. Do we want to keep it
like this or should the "Vi vil skape..."-part be indented aswell?

**Comment by braaar** [comment]
This is surely intentional? I don't know the name for this type of layout

**Comment by braaar** [comment]
kinda like a zig zaggy thing

**Comment by moripen** [comment]
Yeah, but doesnt it then usually go all the way to the left and then all the way to the right? Feels a bit messy to me at least that it is all the way to the left and then in the middle. Maybe its just me?

**Comment by braaar** [comment]
Right aligning text is always tricky since it takes some work to make it look nice depending on the length of the text.

**Comment by moripen** [comment]
The way we did it previously was just to center all of the text, but I guess we can let the others have a say aswell.
