### ISSUE TITLE
Adjustment of the video on the homepage

### ISSUE THREAD

**Issue by AnnaBjerk** [bjerkio/website#63]
The video has to be stretched out to fill out the screen. Right now it jumps to a small square halfway through. 
YouTube elements, such as title, photo of the owner of the video, share button and so on for example, have to be invisible.

**Comment by cobraz** [comment]
@AnnaBjerk @AnneMatilde Maybe we can add some screenshots to make it easier to understand how it should look?

**Comment by AnneMatilde** [comment]
Here is a screenshot of how it looks now:
![image](https://user-images.githubusercontent.com/54155334/111492719-33fe7100-873d-11eb-94d3-f54d1ba9097d.png)

It should rather strech out in width, and crop top and bottom, like this:
![image](https://user-images.githubusercontent.com/54155334/111493277-b1c27c80-873d-11eb-9d3f-8a9e77d9e90a.png)

**Comment by cobraz** [comment]
We're using YouTube-embedding now, we should probably _not_ do that. This is probably easier if we're not locked down in YouTube-embedding.

**Comment by AnnaBjerk** [comment]
@cobraz Could you help @dkostenko-bjerk with this issue when you have time?
