### ISSUE TITLE
Different sized pictures

### ISSUE THREAD

**Issue by HanBrustad** [bjerkio/website#639]
The pictures and headings to the projects are not in line. 
Should they be? 

And also, should they be wider and use the whole width, as the listed projects?

![Skjermbilde 2023-10-30 kl  12 57 35](https://github.com/bjerkio/website/assets/67895695/47bdb4b6-cf5e-428f-8075-c1f42dfeddf6)

**Comment by braaar** [comment]
I agree that it would look nicer if these were the same size!

**Comment by simenandre** [comment]
Done!
