### ISSUE TITLE
Navigation bar has to shrink when scrolling

### ISSUE THREAD

**Issue by AnnaBjerk** [bjerkio/website#71]
The navigation bar will become slimmer when user is scrolling down. 

So from this: 
![Screenshot 2021-03-17 16 57 29](https://user-images.githubusercontent.com/73297506/111498109-f5b78080-8741-11eb-9ce9-df4b3200ce63.png)

To this: 

![image-3](https://user-images.githubusercontent.com/73297506/111498189-0831ba00-8742-11eb-89bc-7a1fbee4abc3.png)

**Comment by AnnaBjerk** [comment]
@dkostenko-bjerk Theremight have been a misunderstanding. The navigation bar has to shrink when people scroll. Right now it just stays the same width. But it'smuch more comfortable to browse when the navigation bar doesn't cover half the page. So it needs to shrink like shown in photos.

**Comment by AnnaBjerk** [comment]
@dkostenko-bjerk This hasn't been fixed yet. The white navigation bar on top does not shrink when scrolling down. It has to become smaller in width when scrolling down.

**Comment by dkostenko-bjerk** [comment]
@AnnaBjerk I think it fixed here (take a look on https://deploy-preview-107--bjerk-website-dev.netlify.app/services/)

**Comment by AnnaBjerk** [comment]
Not sure that's enough "shrinkage"/minimizing. Let's ask @AnneMatilde to give her designer opinion on this! 😺 

/ @AnneMatilde What do you think? Is this consistent with your design?
