### ISSUE TITLE
Update Sanity's schema structure

### ISSUE THREAD

**Issue by dkostenko-bjerk** [bjerkio/website#72]
@cobraz 
Do you want to keep all content in Sanity (even some text in footer on each of the pages)?
Some data can be categorized into entities (as described [here](https://www.sanity.io/docs/donts-and-dos#e3797cd9ae57)) (like services, team members, projects and etc.), but each of the pages has distinctive features from the others, like some images or text that defy a common structure for everyone. Should such data be stored in Sanity too?

**Comment by cobraz** [comment]
The short answer is; it depends.

We need to evaluate what content would change often, and we want to make available for `non-github-users` for changing. IMHO, it should be services, team members, projects etc. Things that can be categories, and we expect to have a _feed_ of.
