### ISSUE TITLE
Site margins

### ISSUE THREAD

**Issue by AnneMatilde** [bjerkio/website#94]
Please adjust margins. All content, including navigation, body and footer content should be aligned – not like this:
![image](https://user-images.githubusercontent.com/54155334/112141186-45c89400-8bd5-11eb-9fcb-b583a33a8bbb.png)

Footer background should also be full width.

**Comment by cobraz** [comment]
Shouldn't the "inner container" also be aligned?

E.g.
```
...[ header ]...
...[  body  ]...
...[ footer ]...
```

Not this:
```
..[  header  ]..
...[  body  ]...
....[footer]....
```

**Comment by AnneMatilde** [comment]
The inner container should be aligned yes, like your first example:

![image](https://user-images.githubusercontent.com/54155334/112142988-90e3a680-8bd7-11eb-9f67-8d83f0892444.png)

**Comment by dkostenko-bjerk** [comment]
Yes, I saw it, there are several issues, where it fixed (e.g. header styles, new footer, etc.)

**Comment by AnneMatilde** [comment]
Inner container is still an issue, as you can see here:
![image](https://user-images.githubusercontent.com/54155334/112435749-73344f80-8d45-11eb-9fc2-6fa9adeee561.png)

**Comment by AnnaBjerk** [comment]
@dkostenko-bjerk Closed this too early. Please, see comment from Anne

**Comment by dkostenko-bjerk** [comment]
@AnneMatilde Has this issue been fixed on the develop branch now?

**Comment by AnnaBjerk** [comment]
@dkostenko-bjerk All the margins seem to be in order now. Let's see what @AnneMatilde will say about this.

**Comment by AnneMatilde** [comment]
Sorry @dkostenko-bjerk I didn't see this. The site margins looks great now.

**Comment by AnneMatilde** [comment]
The margins seems ok on my small screen, but on larger screens the inner container is not the same everywhere.
![Skjermbilde 2021-03-27 kl  13 35 06](https://user-images.githubusercontent.com/54155334/112720888-3f9e2480-8f01-11eb-8605-aa1444b3d9d7.jpg)

The backgrounds are also off, they should both be 100% in width.

**Comment by dkostenko-bjerk** [comment]
@AnneMatilde That is, they shouldn't have a maxWidth prop?

**Comment by AnneMatilde** [comment]
Correct @dkostenko-bjerk – I would like the background to extend all the way out.
